version: '3'
services:

    db-nearmarket:
        build: ./docker/db
        environment:
            MYSQL_DATABASE: 'database'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'pass'
            MYSQL_ROOT_PASSWORD: 'superpass'
        volumes:
            - bddata:/var/lib/mysql
        networks: 
            - internal

    web:
        build: ./docker/web
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:80
        depends_on: 
            - db-nearmarket
        networks: 
            - internal
volumes:
    bddata:
        driver: local

networks:
    public:
        external:
            name: public
    internal:
